baseURL = "https://blacknwhite5.github.io/"
languageCode = "en-us"
title = "jackdaw@blog ~/home"
theme = "hugo-PaperMod"
paginate = 7
canonifyurls = true


enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true


[permalinks]
post = "/:year/:month/:slug/"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[taxonomies]
category = "categories"
tag = "tags"
subcategory = "subcategories"



# -- Navigator --
[languages.en]
languageName = "English"
weight = 1

[[languages.en.menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[[languages.en.menu.main]]
name = "Categories"
url = "categories/"
weight = 10


# <-- param -->
[params.profileMode]
enabled = true
title = "갈까마귀의 연구개발 일상"
subtitle = "까아까악"
imageUrl = "images/logo_jackdaw.png"
#imageTitle = "<title of image as alt>"
imageWidth = 180
imageHeight = 180

#[[params.profileMode.buttons]]
#name = "Archive"
#url = "archives"
#
#[[params.profileMode.buttons]]
#name = "Github"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/blacknwhite5"

#[[params.socialIcons]]
#name = "KakaoTalk"
#url = "https://open.kakao.com/o/sPy1PPT"
