baseURL: 'https://blacknwhite5.github.io/'
languageCode: en-us
title: jackdaw@blog ~/home
theme: hugo-PaperMod
paginate: 7
canonifyurls: true

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
    disableXML: true

permalinks:
  post: '/:year/:month/:slug/'

outputs:
  home:
    - HTML
    - RSS
    - JSON

languages:
  en:
    languageName: English
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 10
        - name: Categories
          url: categories/
          weight: 10
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10

params:
  profileMode:
    enabled: true
    title: 갈까마귀의 연구개발 일상
    subtitle: 까아까악
    imageUrl: images/logo_jackdaw.png
    imageWidth: 180
    imageHeight: 180

    author: Moohyun-Oh
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

  comments: true

  socialIcons:
    - name: Github
      url: 'https://github.com/blacknwhite5'
    - name: email
      url: 'mailto:blacknwhite5@naver.com'


markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
